# Generated by Django 6.0.2 on 2026-05-21 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_parametervalue_delete_productparametervalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameter',
            new_name='Parameters',
        ),
        migrations.RenameModel(
            old_name='ParameterValue',
            new_name='ParameterValues',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
